### ISSUE TITLE
Epic script, but returned empty file...

### ISSUE THREAD

**Issue by anoduck** [SxNade/socksh#1]
Extremely impressive work. Unfortunately, I was not able to get the script to successfully provide any proxies for use. 
I broke the script down command by command and discovered the issue lies within the mulithreading process, where I assume the script is supposed to check the proxies and return the live ones. Which would be lines 88-104. It just doesn't appear to be a command within the process to actually check the proxies and return the active ones. 

Am I missing something?

**Comment by vrikodar** [comment]
Hi @anoduck thanks for reaching out , I suspect this is an issue on your side I have just tested the script and its working perfectly fine and I would also suggest you to clone the fresh repository it might be possible that I have broken code in the releases section and if so I would make a new release. If you are confused with the echo command used to determine if proxy is up or not, you can research more about making a connection to a IP::port from linux using /dev/tcp and also about bash command return codes. Hope this Helps.

and also keep a note that at the end all the proxies are added to a namely **socks5_live_proxies_(date-on-which-script-ran)** file.
This allows you to also maintain a record of all alive proxies Found each day 
For any other issues Feel free to add additional comments

**Comment by anoduck** [comment]
> you can research more about making a connection to a IP::port from **linux** using /dev/tcp and also about bash command return codes. Hope this Helps.

That explains it, not running Linux, running OpenBSD. `/dev/tcp` does not exist on BSD. I might substitute the `echo /dev/tcp` command for `nc -z $IP $PORT` on my fork. 

Regardless, I will be cloning this on my kali installation, and this is some very impressive coding. I salute thee, sir.
